### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by blacksector**
The version you guys have right now does not remove any tags. If you take a look at your website right now: http://cloudboost.github.io/socialNetApp/ I was able to add iframes and such. Next after I have made a fork I tested this code and it works well, I renamed the repository but back to CloudBoost now so that you can easily merge it back just so nothing causes problems. :)

### CODE REVIEW

**Comment by blacksector** [comment]
The second last post on the page shows a test where it did fail to post the iframe but that was through my forked version. Either way, this seems to be a simple way to do it, at least for the purpose of blocking spam as of now. Later on a possibly more elegant patch may come up.

**Comment by nawazdhandala** [comment]
Good idea! :)

**Comment by blacksector** [comment]
Great! Seems pretty safe now :)

**Comment by nawazdhandala** [comment]
Yeah. Thank you so much for help.

**Comment by blacksector** [comment]
No worries, I rather a safer application than a unsafe app that can cause big problems. It was simply overlooked ahah, one thing I learned the hard way, NEVER trust a end user. :)

**Pull request merged**
